github.com:
    users:
        nitkr001-maker:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: nitkr001-maker
